module.exports = [
  { code: '41001010', name: 'TC - Crânio ou Sela Túrcica ou Órbitas' },
  { code: '41001028', name: 'TC - Mastóides ou Orelhas' },
  { code: '41001036', name: 'TC - Face ou Seios da Face' },
  { code: '41001044', name: 'TC - Articulações Temporomandibulares' },
  { code: '41001060', name: 'TC - Pescoço / Partes Moles / Laringe / Tireóide / Faringe / Glândulas Salivares' },
  { code: '41001079', name: 'TC - Tórax' },
  { code: '41001087', name: 'TC - Coração' },
  { code: '41001095', name: 'TC - Abdomen Total' },
  { code: '41001109', name: 'TC - Abdomen Superior' },
  { code: '41001117', name: 'TC - Pelve ou Bacia' },
  { code: '41001125', name: 'TC - Até 3 Segmentos / Coluna Cervical / Dorsal / Lombo-Sacra' },
  { code: '41001133', name: 'TC - Coluna - Segmento Adicional' },
  { code: '41001141', name: 'TC - Articulação / Esterno-clavicular / Ombro / Cotovelo / Punho / Sacroilíacas / Coxa Femural / Joelho / Tornozelo' },
  { code: '41001150', name: 'TC - Segmentos Apendicular (Braço / Antebraço / Mão / Coxa / Perna / Pé)' },
  { code: '41001192', name: 'TC - Escanometria Digital' },
  { code: '41001222', name: 'TC - Para PET Dedicado Oncológico' },
  { code: '41001230', name: 'TC - Angiotomografia Coronária' },
  { code: '41001249', name: 'TC - Artérias de Membros Superior' },
  { code: '41001257', name: 'TC - Cisternografia por Tomografia' },
  { code: '41001265', name: 'TC - Colonoscopia Virtual' },
  { code: '41001270', name: 'TC - Mandíbula' },
  { code: '41001271', name: 'TC - Maxilar' },
  { code: '41001320', name: 'TC - Tomossíntese Digital Mamária' },
  { code: '41001338', name: 'TC - Radiocirurgia Esterotáxica' },
  { code: '41001346', name: 'TC - Multifase (Dinâmica)' },
  { code: '41001354', name: 'TC - Articular Dinâmica' },
  { code: '41001362', name: 'TC - Vias Urinárias (Urotomografia)' },
  { code: '41001125', name: 'TC - Coluna Total' },
  { code: '41001176', name: 'Angiotomografia de Aorta Torácica' },
  { code: '41001370', name: 'Angiotomografia Arterial de Cérebro' },
  { code: '41001397', name: 'Angiotomografia de Pescoço' },
  { code: '41001419', name: 'Angiotomografia de Tórax' },
  { code: '41001435', name: 'Angiotomografia de Abdomen Superior' },
  { code: '41001451', name: 'Angiotomografia Arterial de Pelve' },
  { code: '41001478', name: 'Angiotomografia Arterial de Membro Inferior Direito' },
  { code: '41001478', name: 'Angiotomografia Arterial de Membro Inferior Esquerdo' },
  { code: '41001494', name: 'Angiotomografia Arterial de Membro Superior Direito' },
  { code: '41001494', name: 'Angiotomografia Arterial de Membro Superior Esquerdo' },
  { code: '41001486', name: 'Angiotomografia Venosa de Membro Inferior Direito' },
  { code: '41001486', name: 'Angiotomografia Venosa de Membro Inferior Esquerdo' },
  { code: '41001508', name: 'Angiotomografia Venosa de Membro Superior Direito' },
  { code: '41001400', name: 'Angiotomografia Venosa de Pescoço' },
  { code: '41001443', name: 'Angiotomografia Venosa de Abdomen Superior' },
  { code: '41001460', name: 'Angiotomografia Venosa de Pelve' },
  { code: '41001389', name: 'Angiotomografia Venosa de Cérebro' },
  { code: '41001427', name: 'Angiotomografia Venosa de Tórax' },
  { code: '40808025', name: 'RX - Abdome Agudo' },
  { code: '40805026', name: 'RX - Tórax - 2 incidências' },
  { code: '40804119', name: 'RX - Escanometria' },
  { code: '40804011', name: 'RX - Bacia' },
  { code: '40803015', name: 'RX - Esterno' },
  { code: '40803031', name: 'RX - Costelas - por Hemitórax' },
  { code: '40803040', name: 'RX - Clavícula' },
  { code: '40803058', name: 'RX - Omoplata ou Escápula' },
  { code: '40803066', name: 'RX - Articulação Acromioclavicular' },
  { code: '40803074', name: 'RX - Articulação Escapuloumeral (Ombro)' },
  { code: '40803082', name: 'RX - Braço' },
  { code: '40803090', name: 'RX - Cotovelo' },
  { code: '40803104', name: 'RX - Antebraço' },
  { code: '40803112', name: 'RX - Punho' },
  { code: '40803120', name: 'RX - Mão ou Quirodáctilo' },
  { code: '40803139', name: 'RX - Mãos e Punhos para Idade Óssea' },
  { code: '', name: 'RM - Crânio' },
  { code: '', name: 'RM - Sela Túrcica' },
  { code: '', name: 'RM - Base do Crânio' },
  { code: '', name: 'RM - Órbita' },
  { code: '', name: 'RM - Coluna Cervical' },
  { code: '', name: 'RM - Coluna Lombar / Dorsal' },
  { code: '', name: 'RM - Tórax' },
  { code: '', name: 'RM - Abdome Superior' },
  { code: '', name: 'RM - Pelve' },
  { code: '', name: 'RM - Extremidades (Membro Superior / Inferior)' },
  { code: '', name: 'RM - Articular (de acordo com articulação)' },
  { code: '', name: 'US - Abdomen' },
  { code: '', name: 'US - Abdomen Superior' },
  { code: '', name: 'US - Abdomen Total' },
  { code: '', name: 'US - Aparelho Urinário (Rins+Bexiga)' },
  { code: '', name: 'US - Bolsa Escrotal' },
  { code: '', name: 'US - Estruturas Músculo-Esqueléticas' },
  { code: '', name: 'US - Glândulas Salivares' },
  { code: '', name: 'US - Mamas' },
  { code: '', name: 'US - Obstétrico (vários tipos)' },
  { code: '', name: 'US - Próstata Transretal / Abdominal' },
  { code: '', name: 'US - Doppler Colorido (Carótidas / Membros / Vasos)' },
  { code: '', name: 'Ecocardiograma Transtorácico' }
];
